### ISSUE TITLE
Problem with resources routes

### ISSUE THREAD

**Issue by frank0ch0a** [mmontossi/localizable_routes#6]
I have a problem with resources routes.

```
localized do
  resources :rooms do
    member do
      post 'rented' => 'rooms#rented'
    end
  end
end
```

when I execute rake routes, I got the following error: 

*\* Invoke routes (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
rake aborted!
ArgumentError: Invalid route name: 'messages_pt-BR'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1@global/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:552:in `add_route'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1@global/gems/actionpack-4.2.1/lib/action_dispatch/routing/mapper.rb:1561:in`add_route'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1/gems/translatable_routes-1.4.0/lib/translatable_routes/action_dispatch/mapper.rb:43:in `block in add_route'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1/gems/translatable_routes-1.4.0/lib/translatable_routes/action_dispatch/mapper.rb:14:in`each'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1/gems/translatable_routes-1.4.0/lib/translatable_routes/action_dispatch/mapper.rb:14:in `add_route'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1@global/gems/actionpack-4.2.1/lib/action_dispatch/routing/mapper.rb:1536:in`decomposed_match'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1@global/gems/actionpack-4.2.1/lib/action_dispatch/routing/mapper.rb:1517:in `block in match'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1@global/gems/actionpack-4.2.1/lib/action_dispatch/routing/mapper.rb:1507:in`each'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1@global/gems/actionpack-4.2.1/lib/action_dispatch/routing/mapper.rb:1507:in `match'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1@global/gems/actionpack-4.2.1/lib/action_dispatch/routing/mapper.rb:689:in`map_method'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1@global/gems/actionpack-4.2.1/lib/action_dispatch/routing/mapper.rb:650:in `get'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1@global/gems/actionpack-4.2.1/lib/action_dispatch/routing/mapper.rb:1361:in`block (2 levels) in resources'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1@global/gems/actionpack-4.2.1/lib/action_dispatch/routing/mapper.rb:1394:in `block (2 levels) in collection'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1@global/gems/actionpack-4.2.1/lib/action_dispatch/routing/mapper.rb:816:in`scope'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1@global/gems/actionpack-4.2.1/lib/action_dispatch/routing/mapper.rb:1393:in `block in collection'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1@global/gems/actionpack-4.2.1/lib/action_dispatch/routing/mapper.rb:1665:in`with_scope_level'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1@global/gems/actionpack-4.2.1/lib/action_dispatch/routing/mapper.rb:1392:in `collection'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1@global/gems/actionpack-4.2.1/lib/action_dispatch/routing/mapper.rb:1360:in`block in resources'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1@global/gems/actionpack-4.2.1/lib/action_dispatch/routing/mapper.rb:1676:in `block (2 levels) in resource_scope'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1@global/gems/actionpack-4.2.1/lib/action_dispatch/routing/mapper.rb:816:in`scope'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1@global/gems/actionpack-4.2.1/lib/action_dispatch/routing/mapper.rb:1676:in `block in resource_scope'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1@global/gems/actionpack-4.2.1/lib/action_dispatch/routing/mapper.rb:1665:in`with_scope_level'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1@global/gems/actionpack-4.2.1/lib/action_dispatch/routing/mapper.rb:1675:in `resource_scope'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1@global/gems/actionpack-4.2.1/lib/action_dispatch/routing/mapper.rb:1355:in`resources'
/Users/Frank/Documents/Develop/rumis-web/config/routes.rb:55:in `block (2 levels) in <top (required)>'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1/gems/translatable_routes-1.4.0/lib/translatable_routes/action_dispatch/mapper.rb:8:in`block in localized'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1@global/gems/actionpack-4.2.1/lib/action_dispatch/routing/mapper.rb:816:in `scope'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1/gems/translatable_routes-1.4.0/lib/translatable_routes/action_dispatch/mapper.rb:8:in`localized'
/Users/Frank/Documents/Develop/rumis-web/config/routes.rb:54:in `block in <top (required)>'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1@global/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:432:in`instance_exec'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1@global/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:432:in `eval_block'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1@global/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:410:in`draw'
/Users/Frank/Documents/Develop/rumis-web/config/routes.rb:1:in `<top (required)>'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1@global/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in`load'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1@global/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `block in load'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1@global/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in`load_dependency'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1@global/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1@global/gems/railties-4.2.1/lib/rails/application/routes_reloader.rb:40:in`block in load_paths'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1@global/gems/railties-4.2.1/lib/rails/application/routes_reloader.rb:40:in `each'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1@global/gems/railties-4.2.1/lib/rails/application/routes_reloader.rb:40:in`load_paths'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1@global/gems/railties-4.2.1/lib/rails/application/routes_reloader.rb:16:in `reload!'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1@global/gems/railties-4.2.1/lib/rails/application/routes_reloader.rb:26:in`block in updater'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1@global/gems/activesupport-4.2.1/lib/active_support/file_update_checker.rb:75:in `call'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1@global/gems/activesupport-4.2.1/lib/active_support/file_update_checker.rb:75:in`execute'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1@global/gems/railties-4.2.1/lib/rails/application/routes_reloader.rb:27:in `updater'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1@global/gems/railties-4.2.1/lib/rails/application/routes_reloader.rb:7:in`execute_if_updated'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1@global/gems/railties-4.2.1/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1@global/gems/railties-4.2.1/lib/rails/initializable.rb:30:in`instance_exec'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1@global/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `run'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1@global/gems/railties-4.2.1/lib/rails/initializable.rb:55:in`block in run_initializers'
/Users/Frank/.rvm/rubies/ruby-2.2.0-preview1/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
/Users/Frank/.rvm/rubies/ruby-2.2.0-preview1/lib/ruby/2.2.0/tsort.rb:348:in`block (2 levels) in each_strongly_connected_component'
/Users/Frank/.rvm/rubies/ruby-2.2.0-preview1/lib/ruby/2.2.0/tsort.rb:427:in `each_strongly_connected_component_from'
/Users/Frank/.rvm/rubies/ruby-2.2.0-preview1/lib/ruby/2.2.0/tsort.rb:347:in`block in each_strongly_connected_component'
/Users/Frank/.rvm/rubies/ruby-2.2.0-preview1/lib/ruby/2.2.0/tsort.rb:345:in `each'
/Users/Frank/.rvm/rubies/ruby-2.2.0-preview1/lib/ruby/2.2.0/tsort.rb:345:in`call'
/Users/Frank/.rvm/rubies/ruby-2.2.0-preview1/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
/Users/Frank/.rvm/rubies/ruby-2.2.0-preview1/lib/ruby/2.2.0/tsort.rb:224:in`tsort_each'
/Users/Frank/.rvm/rubies/ruby-2.2.0-preview1/lib/ruby/2.2.0/tsort.rb:205:in `tsort_each'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1@global/gems/railties-4.2.1/lib/rails/initializable.rb:54:in`run_initializers'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1@global/gems/railties-4.2.1/lib/rails/application.rb:352:in `initialize!'
/Users/Frank/Documents/Develop/rumis-web/config/environment.rb:5:in`<top (required)>'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1@global/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1@global/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in`block in require'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1@global/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1@global/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in`require'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1@global/gems/railties-4.2.1/lib/rails/application.rb:328:in `require_environment!'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1@global/gems/railties-4.2.1/lib/rails/application.rb:457:in`block in run_tasks_blocks'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1/gems/rake-10.4.2/lib/rake/task.rb:240:in`block in execute'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1/gems/rake-10.4.2/lib/rake/task.rb:235:in`execute'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/Frank/.rvm/rubies/ruby-2.2.0-preview1/lib/ruby/2.2.0/monitor.rb:211:in`mon_synchronize'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1/gems/rake-10.4.2/lib/rake/task.rb:201:in`block in invoke_prerequisites'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1/gems/rake-10.4.2/lib/rake/task.rb:199:in `each'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1/gems/rake-10.4.2/lib/rake/task.rb:199:in`invoke_prerequisites'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1/gems/rake-10.4.2/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
/Users/Frank/.rvm/rubies/ruby-2.2.0-preview1/lib/ruby/2.2.0/monitor.rb:211:in`mon_synchronize'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1/gems/rake-10.4.2/lib/rake/task.rb:165:in`invoke'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1/gems/rake-10.4.2/lib/rake/application.rb:106:in`block (2 levels) in top_level'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1/gems/rake-10.4.2/lib/rake/application.rb:106:in`block in top_level'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1/gems/rake-10.4.2/lib/rake/application.rb:100:in`top_level'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1/gems/rake-10.4.2/lib/rake/application.rb:176:in`standard_exception_handling'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1/gems/rake-10.4.2/bin/rake:33:in`<top (required)>'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1/bin/rake:23:in `load'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1/bin/rake:23:in`<main>'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1/bin/ruby_executable_hooks:15:in `eval'
/Users/Frank/.rvm/gems/ruby-2.2.0-preview1/bin/ruby_executable_hooks:15:in`<main>'

**Comment by mmontossi** [comment]
Fixed in version 2.0 @frank0ch0a, please note the gem has been renamed to localized_routes

Thanks
